apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  DB_HOST: {{ .Values.productDb.name }}
  DB_PORT: {{ .Values.productDb.service.port | quote }}
  DB_USER: {{ .Values.productDb.credentials.username }}
  DB_NAME: {{ .Values.productDb.credentials.database }}
  TRANSLATION_SERVICE_URL: "http://{{ .Values.translationService.name }}:{{ .Values.translationService.service.port }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: translation-service-config
data:
  DB_HOST: {{ .Values.translationDb.name }}
  DB_PORT: {{ .Values.translationDb.service.port | quote }}
  DB_USER: {{ .Values.translationDb.credentials.username }}
  DB_NAME: {{ .Values.translationDb.credentials.database }}
