apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
type: Opaque
data:
  password: {{ .Values.productDb.credentials.password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: translation-db-secret
type: Opaque
data:
  password: {{ .Values.translationDb.credentials.password | b64enc | quote }}
