"""Initial migration

Revision ID: c0a122490578
Revises:
Create Date: 2026-02-22 20:12:21.099811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a122490578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_request_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('translated_name', sa.Text(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('translated_description', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_name', sa.Text(), nullable=True),
    sa.Column('edited_description', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index(op.f('ix_translations_original_request_id'), 'translations', ['original_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_original_request_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
